version: "3.8"

services:
  house_price_api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: house_price_api
    volumes:
      - ./api:/app
      - ./config:/app/config
      - ./data:/app/data
    ports:
      - "5000:5000"
    restart: always

  house_price_frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: house_price_frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    depends_on:
      - house_price_api
    environment:
      - API_URL=http://house_price_api:5000
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: always
